# Config defaults
baseurl: ''
exclude: ['README.md', 'readme.txt', 'Gemfile', 'CNAME']
permalink: pretty

# Site info
title: 'Denton Works'
email: info@stokedenton.com
description: >-
  Denton Works is place to connect job seekers and local companies whose work has been impacted by COVID-19.

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      type: posts
    values:
      layout: post
      img: /img/blog/default.jpg
  - scope:
      path: 'images'
    values:
      image: true

# Development
sass:
  sass_dir: ./_scss
  style: compact # possible values: nested expanded compact compressed

# Analytics
google_analytics: UA-36441409-5

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
theme: minima

# Google Forms
sheetUrl: https://docs.google.com/spreadsheets/d/1iCpYHV3MeGKyOlSjih4wFuhysAbEfgENLPpkJCO5jIs
forms:
  job_seeker: https://forms.gle/Kerafr72fZ9DxkWAA
  company_profile: https://forms.gle/ms17aoFJw67n7m356
