# Config defaults
baseurl: ''
exclude: ['README.md']
permalink: pretty

# Site info
title: 'Jekyll Serif'
email: info@stokedenton.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

  # Collections
collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

# Development
sass:
  sass_dir: ./_scss
  style: compact # possible values: nested expanded compact compressed

# Analytics
google_analytics: UA-36441409-5

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-seo

# Build settings
markdown: kramdown
theme: minima

# SASS
sass:
  sass_dir: ./_scss
  # style: compressed
